#pragma config(Motor,  port1,           left,          tmotorVex393_HBridge, openLoop, driveLeft)
#pragma config(Motor,  port10,          right,         tmotorVex393_HBridge, openLoop, reversed, driveRight)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

typedef struct {
	float x;
	float y;
} Coor;


Coor cone1;
Coor base1;
Coor pointArea;

static Coor coneList[4];
static Coor position;

void  setup();
void pickupCone();
void placeCone();
void pickUpBase();
void turn(float degree);
void forward(float distance);
task main() {
//The distance between kavi has to be from the cone in order to pick up
float clawRange = 33.3 
setup();
forward(cone1.y - position.y - clawRange);
pickupCone();
turn(-90);
left(base1.x - position.x);
turn(90);
forward(position.y - base1.y - clawRange);
placeCone();
turn(180);
pickUpBase();
forward(position.y - pointArea.y);
park();

}

void setup() {
	cone1.x = 105.8;
	cone1.y = 105.8; 
	base1.x = 117.5;
	base1.y = 117.5;
	pointArea.x = 117.5;
	pointArea.y = 34.9;
	coneList[0] = cone1;
	position.x = 105.8;
	position.y = 58.4;
};

void forward(float distance) {
	motor[left] = 127;
	motor[right] = 89;
	wait1Msec(1000);
	postion.y += distance
	
};